// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  beneficios: dynamic(() => import("./Beneficios")),
  cotizacion: dynamic(() => import("./Cotizacion")),
  experiencia: dynamic(() => import("./Experiencia")),
  inicio: dynamic(() => import("./Inicio")),
  mapa: dynamic(() => import("./Mapa")),
  servicios: dynamic(() => import("./Servicios")),
};
