// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  experiencia: dynamic(() => import("./Experiencia")),
  inicio: dynamic(() => import("./Inicio")),
};
