// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomapageDocumentDataSlicesSlice =
  | CotizacionSlice
  | MapaSlice
  | ExperienciaSlice
  | InicioSlice;

/**
 * Content for Homepage documents
 */
interface HomapageDocumentData {
  /**
   * title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homapage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homapage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomapageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homapage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homapage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homapage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homapage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomapageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomapageDocumentData>,
    "homapage",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavItem {
  /**
   * link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * special field in *Settings → Navigation*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.nav[].special
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  special: prismic.BooleanField;
}

/**
 * Item in *Settings → telefono*
 */
export interface SettingsDocumentDataTelefonoItem {
  /**
   * telefono field in *Settings → telefono*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.telefono[].telefono
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  telefono: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * nombre field in *Settings → telefono*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.telefono[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;
}

/**
 * Item in *Settings → redes*
 */
export interface SettingsDocumentDataRedesItem {
  /**
   * red field in *Settings → redes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.redes[].red
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  red: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * nombre field in *Settings → redes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.redes[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;
}

/**
 * Item in *Settings → correo*
 */
export interface SettingsDocumentDataCorreoItem {
  /**
   * nombre field in *Settings → correo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.correo[].nombre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nombre: prismic.KeyTextField;

  /**
   * correo field in *Settings → correo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.correo[].correo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  correo: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Meta_Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_info: prismic.KeyTextField;

  /**
   * Open_Graph_Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav: prismic.GroupField<Simplify<SettingsDocumentDataNavItem>>;

  /**
   * data_title field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.data_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  data_title: prismic.ImageField<never>;

  /**
   * title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * telefono field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.telefono[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  telefono: prismic.GroupField<Simplify<SettingsDocumentDataTelefonoItem>>;

  /**
   * redes field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.redes[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  redes: prismic.GroupField<Simplify<SettingsDocumentDataRedesItem>>;

  /**
   * correo field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.correo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  correo: prismic.GroupField<Simplify<SettingsDocumentDataCorreoItem>>;

  /**
   * derechos field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.derechos
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  derechos: prismic.RichTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = HomapageDocument | SettingsDocument;

/**
 * Item in *Cotizacion → Default → Primary → contenido*
 */
export interface CotizacionSliceDefaultPrimaryContenidoItem {
  /**
   * data field in *Cotizacion → Default → Primary → contenido*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.contenido[].data
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  data: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * activo field in *Cotizacion → Default → Primary → contenido*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cotizacion.default.primary.contenido[].activo
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  activo: prismic.BooleanField;

  /**
   * datos field in *Cotizacion → Default → Primary → contenido*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.contenido[].datos
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  datos: prismic.KeyTextField;
}

/**
 * Primary content in *Cotizacion → Default → Primary*
 */
export interface CotizacionSliceDefaultPrimary {
  /**
   * contactenos field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.contactenos
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contactenos: prismic.RichTextField;

  /**
   * horas field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.horas
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  horas: prismic.RichTextField;

  /**
   * dias field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.dias
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  dias: prismic.RichTextField;

  /**
   * cotizacion field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.cotizacion
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cotizacion: prismic.RichTextField;

  /**
   * servicio field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Transporte de carga
   * - **API ID Path**: cotizacion.default.primary.servicio
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  servicio: prismic.SelectField<
    "Transporte de carga" | "2da opción" | "3ra opción",
    "filled"
  >;

  /**
   * contenido field in *Cotizacion → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizacion.default.primary.contenido[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contenido: prismic.GroupField<
    Simplify<CotizacionSliceDefaultPrimaryContenidoItem>
  >;
}

/**
 * Default variation for Cotizacion Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CotizacionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CotizacionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cotizacion*
 */
type CotizacionSliceVariation = CotizacionSliceDefault;

/**
 * Cotizacion Shared Slice
 *
 * - **API ID**: `cotizacion`
 * - **Description**: Cotizacion
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CotizacionSlice = prismic.SharedSlice<
  "cotizacion",
  CotizacionSliceVariation
>;

/**
 * Item in *Experiencia → Default → Primary → images*
 */
export interface ExperienciaSliceDefaultPrimaryImagesItem {
  /**
   * image field in *Experiencia → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiencia.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Experiencia → Default → Primary*
 */
export interface ExperienciaSliceDefaultPrimary {
  /**
   * title field in *Experiencia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiencia.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * images field in *Experiencia → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experiencia.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ExperienciaSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for Experiencia Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienciaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExperienciaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Experiencia*
 */
type ExperienciaSliceVariation = ExperienciaSliceDefault;

/**
 * Experiencia Shared Slice
 *
 * - **API ID**: `experiencia`
 * - **Description**: Experiencia
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExperienciaSlice = prismic.SharedSlice<
  "experiencia",
  ExperienciaSliceVariation
>;

/**
 * Item in *Inicio → Default → Primary → images*
 */
export interface InicioSliceDefaultPrimaryImagesItem {
  /**
   * image field in *Inicio → Default → Primary → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * active field in *Inicio → Default → Primary → images*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: inicio.default.primary.images[].active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  active: prismic.BooleanField;
}

/**
 * Primary content in *Inicio → Default → Primary*
 */
export interface InicioSliceDefaultPrimary {
  /**
   * main_info field in *Inicio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.default.primary.main_info
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_info: prismic.RichTextField;

  /**
   * name field in *Inicio → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * images field in *Inicio → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: inicio.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<InicioSliceDefaultPrimaryImagesItem>>;
}

/**
 * Default variation for Inicio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InicioSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InicioSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Inicio*
 */
type InicioSliceVariation = InicioSliceDefault;

/**
 * Inicio Shared Slice
 *
 * - **API ID**: `inicio`
 * - **Description**: Inicio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InicioSlice = prismic.SharedSlice<"inicio", InicioSliceVariation>;

/**
 * Primary content in *Mapa → Default → Primary*
 */
export interface MapaSliceDefaultPrimary {
  /**
   * map field in *Mapa → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: mapa.default.primary.map
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  map: prismic.GeoPointField;
}

/**
 * Default variation for Mapa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MapaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Mapa*
 */
type MapaSliceVariation = MapaSliceDefault;

/**
 * Mapa Shared Slice
 *
 * - **API ID**: `mapa`
 * - **Description**: Mapa
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MapaSlice = prismic.SharedSlice<"mapa", MapaSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomapageDocument,
      HomapageDocumentData,
      HomapageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItem,
      SettingsDocumentDataTelefonoItem,
      SettingsDocumentDataRedesItem,
      SettingsDocumentDataCorreoItem,
      AllDocumentTypes,
      CotizacionSlice,
      CotizacionSliceDefaultPrimaryContenidoItem,
      CotizacionSliceDefaultPrimary,
      CotizacionSliceVariation,
      CotizacionSliceDefault,
      ExperienciaSlice,
      ExperienciaSliceDefaultPrimaryImagesItem,
      ExperienciaSliceDefaultPrimary,
      ExperienciaSliceVariation,
      ExperienciaSliceDefault,
      InicioSlice,
      InicioSliceDefaultPrimaryImagesItem,
      InicioSliceDefaultPrimary,
      InicioSliceVariation,
      InicioSliceDefault,
      MapaSlice,
      MapaSliceDefaultPrimary,
      MapaSliceVariation,
      MapaSliceDefault,
    };
  }
}
